---
name: bootstrap-elemental-baseconfig
---
SilverStripe\Core\Injector\Injector:
  DNADesign\Elemental\Extensions\ElementalPageExtension:
    class: Syntro\SilverStripeElementalBaseitems\Extensions\BootstrapElementalPageExtension
