---
name: bootstrap-elemental-baseconfig
---
DNADesign\Elemental\Models\BaseElement:
  controller_template: SectionHolder
  inline_editable: false
  extensions:
    - Syntro\SilverStripeElementalBaseitems\Extensions\BootstrapBaseElementExtension

DNADesign\Elemental\Models\ElementContent:
  block_name: content-section
